//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by NHibernate.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;

namespace KMS.Model
{
	/// <summary>
	/// a class mapping for the table: dbo.KnowledgeKnowledgeClassAssociation
	/// </summary>
	public  partial class KnowledgeKnowledgeClassAssociationInfo 
	{

	#region private fields
		Int32 _kKCId;	
		DateTime? _timeStamp;	
		KnowledgeInfo _knowledgeInfo;	/* KnowledgeId */
		KnowledgeClassInfo _knowledgeClassInfo;	/* KnowledgeClassId */
	#endregion
		
	#region getter/setters		
		/// <summary>
		///		
		/// </summary>
		public virtual Int32 KKCId
		{
			get{ return _kKCId; }
			set{ _kKCId = value; }
		}
		/// <summary>
		///		
		/// </summary>
		public virtual DateTime? TimeStamp
		{
			get{ return _timeStamp; }
			set{ _timeStamp = value; }
		}
		/// <summary>
		///		
		/// </summary>
		public virtual KnowledgeInfo KnowledgeInfo
		{
			get{ return _knowledgeInfo; }
			set{ _knowledgeInfo = value; }
		}
		/// <summary>
		///		
		/// </summary>
		public virtual KnowledgeClassInfo KnowledgeClassInfo
		{
			get{ return _knowledgeClassInfo; }
			set{ _knowledgeClassInfo = value; }
		}
	#endregion
	}
}