//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by NHibernate.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;

namespace KMS.Model
{
	/// <summary>
	/// a class mapping for the table: dbo.T_ResourceTagAssociation
	/// </summary>
	public  partial class ResourceTagAssociationInfo 
	{

	#region private fields
		Int32 _resourceTagId;	
		ResourceInfo _resourceInfo;	/* ResourceId */
		TagInfo _tagInfo;	/* TagId */
	#endregion
		
	#region getter/setters		
		/// <summary>
		///		
		/// </summary>
		public virtual Int32 ResourceTagId
		{
			get{ return _resourceTagId; }
			set{ _resourceTagId = value; }
		}
		/// <summary>
		///		
		/// </summary>
		public virtual ResourceInfo ResourceInfo
		{
			get{ return _resourceInfo; }
			set{ _resourceInfo = value; }
		}
		/// <summary>
		///		
		/// </summary>
		public virtual TagInfo TagInfo
		{
			get{ return _tagInfo; }
			set{ _tagInfo = value; }
		}
	#endregion
	}
}