//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by NHibernate.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace KMS.Model
{
	/// <summary>
	/// a class mapping for the table: dbo.T_Tag
	/// </summary>
	public  partial class TagInfo 
	{

	#region private fields
		Int32 _tagId;	
		String _description;	
		String _name;	
		IList<ResourceTagAssociationInfo> _resourceTagAssociationInfos = new List<ResourceTagAssociationInfo>();	
	#endregion
		
	#region getter/setters		
		/// <summary>
		///		
		/// </summary>
		public virtual Int32 TagId
		{
			get{ return _tagId; }
			set{ _tagId = value; }
		}
		/// <summary>
		///		
		/// </summary>
		public virtual String Description
		{
			get{ return _description; }
			set{ _description = value; }
		}
		/// <summary>
		///		
		/// </summary>
		public virtual String Name
		{
			get{ return _name; }
			set{ _name = value; }
		}
		/// <summary>
		///		
		/// </summary>
		public virtual IList<ResourceTagAssociationInfo> ResourceTagAssociationInfos
		{
			get{ return _resourceTagAssociationInfos; }
			set{ _resourceTagAssociationInfos = value; }
		}
	#endregion
	}
}