//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by NHibernate.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace KMS.Model
{
	/// <summary>
	/// a class mapping for the table: dbo.Knowledge
	/// </summary>
	public  partial class KnowledgeInfo 
	{

	#region private fields
		Int32 _knowledgeId;	
		String _content;	
		String _description;	
		String _name;	
		DateTime? _timeStamp;	
		IList<KnowledgeKnowledgeClassAssociationInfo> _knowledgeKnowledgeClassAssociationInfos = new List<KnowledgeKnowledgeClassAssociationInfo>();	
		IList<KnowledgeTagAssociationInfo> _knowledgeTagAssociationInfos = new List<KnowledgeTagAssociationInfo>();	
	#endregion
		
	#region getter/setters		
		/// <summary>
		///		
		/// </summary>
		public virtual Int32 KnowledgeId
		{
			get{ return _knowledgeId; }
			set{ _knowledgeId = value; }
		}
		/// <summary>
		///		
		/// </summary>
        public virtual String Content
		{
			get{ return _content; }
			set{ _content = value; }
		}
		/// <summary>
		///		
		/// </summary>
		public virtual String Description
		{
			get{ return _description; }
			set{ _description = value; }
		}
		/// <summary>
		///		
		/// </summary>
		public virtual String Name
		{
			get{ return _name; }
			set{ _name = value; }
		}
		/// <summary>
		///		
		/// </summary>
		public virtual DateTime? TimeStamp
		{
			get{ return _timeStamp; }
			set{ _timeStamp = value; }
		}
		/// <summary>
		///		
		/// </summary>
		public virtual IList<KnowledgeKnowledgeClassAssociationInfo> KnowledgeKnowledgeClassAssociationInfos
		{
			get{ return _knowledgeKnowledgeClassAssociationInfos; }
			set{ _knowledgeKnowledgeClassAssociationInfos = value; }
		}
		/// <summary>
		///		
		/// </summary>
		public virtual IList<KnowledgeTagAssociationInfo> KnowledgeTagAssociationInfos
		{
			get{ return _knowledgeTagAssociationInfos; }
			set{ _knowledgeTagAssociationInfos = value; }
		}
	#endregion
	}
}